spring.application.name: kopring-study
spring.profiles.active: local

spring:
  config:
    import:
      - rdb.yml
      - user.yml

---
spring.config.activate.on-profiles: local


---
spring.config.activate.on-profiles: dev
